version: '3.8'

# networks: 
#   ep-mern: 
#     external: true

services:
  search-service:
    image: third-party-api-ms:latest
    # image: ep-mern-searchservice:v3
    container_name: ep-thirdparty-ms 
    # stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./microservice
    ports:
      - "3001:3001"